My solution
mate-academy/py-blog pull request #133
Opened 2023-07-17 15:12 UTC by kovaliskoveronika

![add_comments_no_login](https://github.com/mate-academy/py-blog/assets/89770594/e2180f5b-9531-43a5-9bc3-2844c22b65ba)
![commet_login](https://github.com/mate-academy/py-blog/assets/89770594/428d8d84-230d-4d31-9538-b29255835a40)
![post list](https://github.com/mate-academy/py-blog/assets/89770594/b5f780ad-e6a4-490a-b8fc-7c4a79e6088b)
![post_detail](https://github.com/mate-academy/py-blog/assets/89770594/5439c60a-600e-4f93-80fb-2f4f6bc3432a)

2023-07-18 10:07 UTC, YuriiKindrat requested changes

2023-07-18 10:07 UTC, YuriiKindrat commented on blog/models.py
> +    owner = models.ForeignKey(to=User,
it is better to use AUTH_USER_MODEL here

2023-07-18 10:07 UTC, YuriiKindrat commented on blog/models.py
> +    user = models.ForeignKey(to=User,
same

2023-07-18 10:07 UTC, YuriiKindrat commented on templates/base.html
> +</html>
no blank line at the end of file

2023-07-18 10:07 UTC, YuriiKindrat commented on templates/base.html
> +</html>
fix this everywhere

2023-07-19 09:40 UTC, Oleg-s-s approved these changes
:+1:

2023-10-30 18:37 UTC, closed without merging