Blog
mate-academy/py-blog pull request #14
Opened 2023-01-18 15:42 UTC by bythewaters

2023-01-18 15:52 UTC, bythewaters commented
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/114418942/213220708-4de76e52-1398-42f5-a705-fc08994d01cb.png">

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/114418942/213220923-e864077e-78db-4693-bb28-d9bc61a7e24c.png">

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/114418942/213221249-1ed03738-586e-4918-b76e-057ca98dfef2.png">

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/114418942/213221376-211358f8-a7b3-437e-a76d-9307fe7f551f.png">

2023-01-19 09:57 UTC, Serhii-Leonenko requested changes

2023-01-19 09:57 UTC, Serhii-Leonenko commented on blog/urls.py
> +        "post/<int:pk>/",
```suggestion
        "posts/<int:pk>/",
```

2023-01-19 09:57 UTC, Serhii-Leonenko commented on blog/views.py
> +            )
```suggestion
            comment = Commentary.objects.create(
                post=Post.objects.get(id=pk),
                user=request.user, 
                content=content
            )
```

Fix indentation

2023-01-20 09:18 UTC, Serhii-Leonenko approved these changes
Good job!

2024-06-10 16:56 UTC, closed without merging