Develop
mate-academy/py-blog pull request #37
Opened 2023-03-10 11:47 UTC by Soobig666

2023-03-10 11:55 UTC, Soobig666 commented
<img width="1439" alt="Снимок экрана 2023-03-10 в 13 54 37" src="https://user-images.githubusercontent.com/113036822/224309773-5f862ffb-661b-4abb-b055-e7df438b1090.png">
<img width="1440" alt="Снимок экрана 2023-03-10 в 13 53 50" src="https://user-images.githubusercontent.com/113036822/224309792-26b6407f-5e50-4364-89d1-a60964b3a5c4.png">
<img width="1440" alt="Снимок экрана 2023-03-10 в 13 54 12" src="https://user-images.githubusercontent.com/113036822/224309796-b7aa07a6-5e2b-4014-861c-fcd5feeabf7d.png">
<img width="1440" alt="Снимок экрана 2023-03-10 в 13 54 24" src="https://user-images.githubusercontent.com/113036822/224309799-50cd7c69-ea56-4dd0-ab94-54c4b82a9931.png">

2023-03-13 13:58 UTC, ArsenPidhoretskyi requested changes
Add .idea to gitignore, also then use get rm cached
Also this url does not work http://127.0.0.1:8000/posts/1/comment/

2023-03-13 13:58 UTC, ArsenPidhoretskyi commented on .gitignore
> +db.sqlite3
Add empty line at the end of file

2023-03-13 18:23 UTC, Bohdan-Salamakha commented on blog/views.py
> +    def form_valid(self, form) -> HttpResponse:
add form typehint

2023-03-13 18:23 UTC, Bohdan-Salamakha commented on blog/views.py
> +    def form_valid(self, form) -> HttpResponse:
add form typehint

2023-03-13 18:24 UTC, Bohdan-Salamakha requested changes
remove .idea from git

2023-03-15 10:16 UTC, Soobig666 commented on blog/views.py
> +    def form_valid(self, form) -> HttpResponse:
> typehint

какой tipehint? я не понимаю

2023-03-15 10:17 UTC, Soobig666 commented
> Add .idea to gitignore, also then use get rm cached
> Also this url does not work http://127.0.0.1:8000/posts/1/comment/
 а разве эта ссылка должна работать? я такую не создавал. Если ты хочешь что бы я такую создал, то что в этой ссылке должно быть? отдельно написанный комментарий ?

2023-03-15 13:52 UTC, ArsenPidhoretskyi commented
Ну глянь свох urls) Вона в тебе така може бути)

2023-03-16 10:55 UTC, closed without merging